### ISSUE TITLE
ProtoCodec get original proto message

### ISSUE THREAD

**Issue by suederade** [vimeo/galaxycache#17]
I love the idea of all of this and the hotcache, but I cannot for the life of me figure out how to use the protocodec.

If I pass in a protocodec in my GetterFunc that puts a proto into the codec:

    inProtoCodec := &ProtoCodec{
		Msg: &testpb.TestMessage{
			Name: proto.String("TestName"),
			City: proto.String("TestCity"),
		},
	}

And then I call get for whatever key that proto was for, how do I actually get this proto back?

    &testpb.TestMessage{
			Name: proto.String("TestName"),
			City: proto.String("TestCity"),
		}

If I try to convert it to the original type (i.e. testpb.TestMessage) the proto struct generated by protobuf (protoc) does not implement `proto.Message`

**Comment by dfinkel** [comment]
Good question. we should definitely add an example.

It's essentially the same thing on the other end.
When you call [`(*Galaxy).Get()`](https://pkg.go.dev/github.com/vimeo/galaxycache@v0.0.0-20201023165603-ff53c5f8b706#Galaxy.Get), the second argument is the codec, so you call that as:
```go
outprotoCodec := &ProtoCodec{
	Msg: &testpb.TestMessage{},
}
getErr := g.Get(ctx, "somekey", outprotoCodec)
```

As long as `Get()` succeeds, `outProtoCodec` now has the unmarshaled message.

The important bit is that the `Msg` field has to be populated with an instance of the relevant protobuf message (preferably empty) for it to find the `Unmarshal()` method.

**Comment by suederade** [comment]
So I actually got that part, but for some reason the only way I am actually able to get the proto is if I Marshall it again. Not sure why but protoc isn't creating structs that implement `proto.Message`. Does this seem correct?

    out := &productV1.ProductsRequest{}
	outProtoCodec := &protocodec.ProtoCodec{
		Msg: &productV1.ProductsRequest{},
	}
	err := a.galaxy.Get(ctx, key, outProtoCodec)
	if err != nil {
		return nil, errs.Wrap(err)
	}

	data, err := outProtoCodec.MarshalBinary()
	if err != nil {
		return nil, errs.Wrap(err)
	}

	err = proto.Unmarshal(data, out)
	if err != nil {
		return nil, errs.Wrap(err)
	}
	return out, err`

**Comment by dfinkel** [comment]
(sorry about the delay)

You definitely should not need to re-marshal/unmarshal the message.

I just checked with a `protoc-gen-go` version from `master` and a round-trip through protocodec works fine.

`protocodec.UnmarshalBInary` doesn't have any idea what type it's unmarshaling into other than the value in the `Msg` field, so that must be set for `UnmarshalBinary` to work. In general, rather than use a type-assert, I recommend holding onto a reference to the message you're passing to the `protocodec`.

One thing to note is that the direct struct-type doesn't implement any of the message interfaces.

So, a recommended example would actually be:

```go
outMsg := testpb.TestMessage{}
outprotoCodec := &ProtoCodec{
	Msg: &outMsg,
}
unmarshalErr := outprotoCodec.UnmarshalBinary(somebytes)
// or getErr := g.Get(ctx, "somekey", outprotoCodec)
```

If you do want to use a type-assert, though, you'd need to do this:
```go
var out *productV1.ProductsRequest
out = outProtoCodec.Msg.(*productV1.ProductsRequest)
```

**Comment by sergiosalvatore** [comment]
Given its age, I'm going to close this issue.  Feel free to re-open if needed...
